"""empty message

Revision ID: 77172297f10f
Revises: 4e209d0f442d
Create Date: 2021-07-30 09:20:34.140178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77172297f10f'
down_revision = '4e209d0f442d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lastComment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('nestedComment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('open_graph', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('img', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('href', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_graph', schema=None) as batch_op:
        batch_op.drop_column('href')
        batch_op.drop_column('url')
        batch_op.drop_column('description')
        batch_op.drop_column('img')
        batch_op.drop_column('title')

    with op.batch_alter_table('nestedComment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('lastComment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
